image: golang:latest
variables:
  
stages: 
  - build
compile:
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - GOOS=windows GOARCH=AMD64 go build ${CI_PROJECT_DIR}/cmd/hostfile -o ${CI_PROJECT_DIR}/build/hostfile64.exe
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/build/hostfile64.exe
  only:
    - master
  
  